# Generated by Django 3.1.7 on 2021-03-02 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='emplyefom',
            fields=[
                ('emp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('emp_name', models.CharField(max_length=225)),
                ('emp_mail', models.EmailField(max_length=225)),
                ('emp_job', models.CharField(max_length=225)),
                ('join_date', models.DateTimeField()),
            ],
        ),
    ]
